//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viragkereskedes_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class details : enOrders
    {
        public int product_number { get; set; }
        public int product_amount { get; set; }
    
        public virtual enProducts pid { get; set; }
        public virtual enOrders oid { get; set; }
    }
}
