//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viragkereskedes_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cnViragkereskedes : DbContext
    {
        public cnViragkereskedes()
            : base("name=cnViragkereskedes")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<enProducts> Products { get; set; }
        public virtual DbSet<enCategories> Categories { get; set; }
        public virtual DbSet<enBouquet> Bouquet { get; set; }
        public virtual DbSet<enAccessories> Accessories { get; set; }
        public virtual DbSet<enOrders> Orders { get; set; }
        public virtual DbSet<enUsers> Users { get; set; }
    }
}
