//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viragkereskedes_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class enAccessory_vs_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enAccessory_vs_product()
        {
            this.enProducts = new HashSet<enProduct>();
        }
    
        public int accessory_amount { get; set; }
        public int Id { get; set; }
    
        public virtual enAccessory enAccessory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enProduct> enProducts { get; set; }
    }
}
