//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viragkereskedes_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class enBouquet
    {
        public int bouquet_id { get; set; }
        public int bouquet_fee { get; set; }
    
        public virtual enProducts pid { get; set; }
    }
}
