//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viragkereskedes_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class enOrders
    {
        public int order_id { get; set; }
        public int order_amount { get; set; }
        public System.DateTime order_date { get; set; }
        public bool order_ordered { get; set; }
    
        public virtual enUsers uid { get; set; }
    }
}
