//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viragkereskedes_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class enProducts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enProducts()
        {
            this.cid = new HashSet<enCategories>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public int product_price { get; set; }
        public bool product_onsale { get; set; }
        public string product_description { get; set; }
        public byte product_icon { get; set; }
        public bool product_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enCategories> cid { get; set; }
    }
}
