//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viragkereskedes_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class enProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enProduct()
        {
            this.enBouquets = new HashSet<enBouquet>();
            this.BouquetId = new HashSet<enBouquet>();
            this.enAccessory_vs_product = new HashSet<enAccessory_vs_product>();
            this.enOrder_detail = new HashSet<enOrder_detail>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public int product_price_net { get; set; }
        public int product_fees { get; set; }
        public bool product_sale { get; set; }
        public string product_description { get; set; }
        public string product_icon { get; set; }
        public bool product_active { get; set; }
        public int product_price_gross { get; set; }
    
        public virtual enCategory enCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enBouquet> enBouquets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enBouquet> BouquetId { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enAccessory_vs_product> enAccessory_vs_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enOrder_detail> enOrder_detail { get; set; }
    }
}
